name: Linters

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  security_lint:
    runs-on: ubuntu-latest
    name: Security Linter
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Security linter
      run: python .github/tools/linter-security.py .

  unittests_lint:
    runs-on: ubuntu-latest
    name: Unit Tests Linter
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Unit Tests linter
      run: python .github/tools/linter-unittests.py .

  directory_lint:
    runs-on: ubuntu-latest
    name: Directory Linter
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Directory linter
      run: python .github/tools/linter-directory.py .
